### ISSUE TITLE
Addr Calculation

### ISSUE THREAD

**Issue by rishikakushwah16** [SAITPublic/PIMSimulator#12]
Hi, I wanted to understand, how address is calculated for mapping in the following line of code:

mem->addTransaction(false, addr, tag, buffer);

Thank you!

**Comment by iamshcha** [comment]
https://github.com/SAITPublic/PIMSimulator/blob/b464dde014a5b137a510e53e95cfa9c706e77fee/src/tests/KernelAddrGen.cpp#L25-L55
