### ISSUE TITLE
Timing Model

### ISSUE THREAD

**Issue by Arash1381-y** [SAITPublic/PIMSimulator#16]
Hello,

I have a couple of questions regarding the timing model and data flow for PIM (Processing In Memory) instructions.
### Question 1: Latency of Operand Reads in doPIM()

In the doPIM() function, operands (which may be data in banks) are read. Do we account for the latency of this request? Specifically, the function `void PIMRank::readOpd(int pb, BurstType &bst, PIMOpdType type, BusPacket *packet, int idx, bool is_auto, bool is_mac)`appears to handle the logical part of reading an operand. However, I am uncertain where to find the cycle count for this operation.
### Question 2: Data Flow and Control of PCU

Additionally, I have a question about the data flow related to the PCU (Processing Control Unit). Given that the PCU is located near the sense amplifiers, is the data for the PCU provided directly from the active row? If so, does the memory controller send the read request to the banks, or is this managed by the PIM unit controllers?

Thanks

**Comment by iamshcha** [comment]
1. Yes, a memory command triggers a PIM operation, and the PIM operation, including `readOpd()` which fetches operands from bank or register, is executed within DRAM timing constraints.

2. The data can be fetched directly from an active row into a register in the PIM Block. The bank address where the data is located comes from the memory controller, and the register address is controlled by the PIM block. As mentioned above, the entire process performed in one memory command.
