### ISSUE TITLE
columns size

### ISSUE THREAD

**Issue by Arash1381-y** [SAITPublic/PIMSimulator#18]
The current implementation of the bank read/write operations involves reading or writing 256-bit chunks of data  (it is even larger than the number of columns specified in the sasmung.ini file) . This behavior is exemplified in the provided log of a FILL instruction transaction. The GRF (General Register File) log indicates that each read command retrieves 16 values, each containing 16 bits, from a specific column and row, resulting in a 256-bit data transfer.

Here is the log of the transaction: (values in register files are decimal values) 
```
READ ch0 ra0 bg0 b0 r0 c0|| [0] FILL GRF_A[0], EVEN_BANK @ 2314
PIM ID : 0
[GRF_A][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[GRF_B][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[BANK_R][0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,0000000000000000 ,]
[CMD]10011000100000000000000000000000(FILL GRF_A[0], EVEN_BANK)
[GRF_A][ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
[GRF_B][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ][ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]
----------
```

As you can see, 16 values, each containing 16 bits, are read with a single read command. Even if the fill instruction is a special case that reads the entire row (I thought that maybe the GRF has access to the whole active row, allowing it to read all the data in the row buffer), it is still illogical to fit this amount of data in a single row. A single row with 128 columns can hold 8 half-precision floating-point numbers, but in the simulator, each row may contain up to 512 half-precision floating-point numbers (calculated as 32[col/bit lines] * 256[burst length] / 16[size of floating point number]).

**Comment by iamshcha** [comment]
I think you may need to check the code to see what `NUM_COLS` means in DRAMSim2's configuration. The size of a row in bits is `NUM_COLS` * `DEVICE_WIDTH`. Currently, based on the provided ini file, the internal code calculates the size of a row to be `128 * 64 = 8192 bits`.
Please see `src/MemorySystem.cpp`.

**Comment by Arash1381-y** [comment]
I got it. thanks for your quick reply.
(For anyone with the same issue: https://github.com/umd-memsys/DRAMSim2/blob/master/MemorySystem.cpp#L89)
