### ISSUE TITLE
SB mode to HAB mode conversion issue

### ISSUE THREAD

**Issue by jeageun** [SAITPublic/PIMSimulator#2]
Based on the paper and the code I read, from single bank to half or all bank mode conversion would happen when we touch specific region of DRAM. 
In the simulator, when it generates the command trace, it set row and column to 0x27ff, 0x1f 
https://github.com/SAITPublic/PIMSimulator/blob/dev/src/tests/PIMKernel.cpp#L111

Then, when it actually launch the command, it checks if it is 0x17ff, 0x1f
https://github.com/SAITPublic/PIMSimulator/blob/dev/src/Rank.cpp#L404

It seems weird and I can't understand why it works in this way. 
With HBM_64ch case, it somehow works, but when I change the channel size, it miss this condition.

Is it an intended behavior? if so, why? Does the packet needs to be manipulated in memory controller before it actually launch?

**Comment by jeageun** [comment]
Similar logic also exist in various places;
Set the row using (1<<13) for special operation like , but always compares with 1<<12
https://github.com/SAITPublic/PIMSimulator/blob/6d8e5f9312280a6a77e731bfe45ae637a58d3e75/src/tests/PIMKernel.cpp#L61-L72
https://github.com/SAITPublic/PIMSimulator/blob/6d8e5f9312280a6a77e731bfe45ae637a58d3e75/src/tests/PIMKernel.cpp#L36-L53

**Comment by iamshcha** [comment]
The row address handled by DRAM is converted before and after via ```changeRA12RA13(addr)```.
https://github.com/SAITPublic/PIMSimulator/blob/6d8e5f9312280a6a77e731bfe45ae637a58d3e75/src/MultiChannelMemorySystem.cpp#L458-L484

Therefore, as you mentioned, the 12th and 13th row addresse bits differ in ```PIMKernel.cpp``` (generation from S/W side) and ```Rank.cpp```(DRAM side).

This simulator is used for PIM simulations, but it can also be used directrly with PIM Library. In this case, the input of the simulator is memory commands generated from ```PIMLibrary```, which is a S/W stack, not ```PIMKernel.cpp```, and this simulator can verify its functionality using the above path. 

If you want to change this simulator, you need to consider this.

**Comment by jeageun** [comment]
Is there a reason why it is implemented in that way? If it is only for compatibility, is there any document about these kind of rules to keep it compatible with PIMLibrary or other repositories in OneMCC?

**Comment by iamshcha** [comment]
For the compatibility of the PIM simulator with the PIM library, consider only swaps in 12th and 13th rows.

However, in order to use different simulator configurations or to integrate with other simulators, it would be better to separate  the simulatoin and emulation paths with PIM library for this part, and we'll consider this in the next update.
