### ISSUE TITLE
Question about PIM timing

### ISSUE THREAD

**Issue by youngsukpp** [SAITPublic/PIMSimulator#3]
Hello, I have a question about PIM timing behavior.

As far as I know, when PIM operates add, mul, mac operations, it consumes some cycles.
I tried to find such PIM timings inside the simulator, but couldn't find any.
Is it an intended design? If so, what is the reason for not considering PIM timing?

Thanks!

**Comment by iamshcha** [comment]
In this simulator, the PIM operation consumes the PIM timing of tCCD_L. If there are multiple PIM operations (add, mul, mac..), it is equivalent to repeating multiple tCCD_L times.

**Comment by youngsukpp** [comment]
@iamshcha Thanks for your kind anwer. It helped a lot!
